{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "76be6cf6-3d51-4f36-b574-9e7bc0e61798",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-07-23 08:32:20.542 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.054 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Python312\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-07-23 08:32:21.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.060 Session state does not function when running a script without `streamlit run`\n",
      "2025-07-23 08:32:21.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.063 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.072 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-23 08:32:21.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "\n",
    "# Load the logistic regression model and feature columns\n",
    "model = joblib.load(\"logistic_model.pkl\")\n",
    "model_columns = joblib.load(\"model_columns.pkl\")\n",
    "\n",
    "st.title(\"Accident Severity Predictor\")\n",
    "\n",
    "st.write(\"Predict whether an accident is **fatal** or **non-fatal** based on road and environment conditions.\")\n",
    "\n",
    "# Input fields - make sure they match your dataset's original values\n",
    "junction = st.selectbox(\"Junction Control\", ['None', 'Give Way', 'Auto Traffic Signal', 'Stop', 'Authorised Person'])\n",
    "light = st.selectbox(\"Light Conditions\", ['Daylight', 'Darkness - lights lit', 'Darkness - lights unlit'])\n",
    "surface = st.selectbox(\"Road Surface Conditions\", ['Dry', 'Wet or damp', 'Snow', 'Frost or ice'])\n",
    "road_type = st.selectbox(\"Road Type\", ['Single carriageway', 'Dual carriageway', 'One way street'])\n",
    "weather = st.selectbox(\"Weather Conditions\", ['Fine no high winds', 'Raining no high winds', 'Snowing', 'Fog or mist'])\n",
    "vehicle = st.selectbox(\"Vehicle Type\", ['Car', 'Motorcycle', 'Bus', 'Truck', 'Bicycle'])\n",
    "\n",
    "# Predict button\n",
    "if st.button(\"Predict Severity\"):\n",
    "    # Create input DataFrame\n",
    "    input_dict = {\n",
    "        'Junction_Control': junction,\n",
    "        'Light_Conditions': light,\n",
    "        'Road_Surface_Conditions': surface,\n",
    "        'Road_Type': road_type,\n",
    "        'Weather_Conditions': weather,\n",
    "        'Vehicle_Type': vehicle\n",
    "    }\n",
    "\n",
    "    input_df = pd.DataFrame([input_dict])\n",
    "\n",
    "    # One-hot encode input\n",
    "    input_encoded = pd.get_dummies(input_df)\n",
    "    input_encoded = input_encoded.reindex(columns=model_columns, fill_value=0)\n",
    "\n",
    "    # Predict\n",
    "    prediction = model.predict(input_encoded)[0]\n",
    "    probability = model.predict_proba(input_encoded)[0][1]\n",
    "\n",
    "    result = \"Fatal\" if prediction == 1 else \"Non-Fatal\"\n",
    "    \n",
    "    st.success(f\" Predicted Severity: **{result}**\")\n",
    "    st.info(f\"Probability of Fatality: **{probability:.2f}**\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "18038b2d-1078-4a83-9912-d6426e02cd11",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
